### ISSUE TITLE
Rust char variable declaration

### ISSUE THREAD

**Issue by anhdat** [dgoldsb/advent-of-code-2020#1]
https://github.com/dgoldsb/advent-of-code-2020/blob/f33c2e590c4a64ff1254773925a6450c4071a75f/rust/day_03/src/main.rs#L17

`char` variable declaration syntax is with single quotes. So we can write this as `let tree = '#';`. Also, you may want to make it a constant or even better, [a static constant](https://doc.rust-lang.org/rust-by-example/custom_types/constants.html).

**Comment by dgoldsb** [comment]
🤦‍♂️ Thank you!

**Comment by dgoldsb** [comment]
Addressed in d42c33430ee83f1fc5b3dd7b40ff94c4e80ab91b 😁
